# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import codebase_pb2 as codebase__pb2
from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in codebase_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodebaseServiceStub(object):
    """CodebaseService manages user codebases (file folders)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCodebase = channel.unary_unary(
                '/sandbox.v1.CodebaseService/CreateCodebase',
                request_serializer=codebase__pb2.CreateCodebaseRequest.SerializeToString,
                response_deserializer=codebase__pb2.Codebase.FromString,
                _registered_method=True)
        self.GetCodebase = channel.unary_unary(
                '/sandbox.v1.CodebaseService/GetCodebase',
                request_serializer=codebase__pb2.GetCodebaseRequest.SerializeToString,
                response_deserializer=codebase__pb2.Codebase.FromString,
                _registered_method=True)
        self.ListCodebases = channel.unary_unary(
                '/sandbox.v1.CodebaseService/ListCodebases',
                request_serializer=codebase__pb2.ListCodebasesRequest.SerializeToString,
                response_deserializer=codebase__pb2.ListCodebasesResponse.FromString,
                _registered_method=True)
        self.DeleteCodebase = channel.unary_unary(
                '/sandbox.v1.CodebaseService/DeleteCodebase',
                request_serializer=codebase__pb2.DeleteCodebaseRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.UploadFiles = channel.stream_unary(
                '/sandbox.v1.CodebaseService/UploadFiles',
                request_serializer=codebase__pb2.UploadChunk.SerializeToString,
                response_deserializer=codebase__pb2.UploadResult.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/sandbox.v1.CodebaseService/DownloadFile',
                request_serializer=codebase__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=codebase__pb2.FileChunk.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/sandbox.v1.CodebaseService/ListFiles',
                request_serializer=codebase__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=codebase__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class CodebaseServiceServicer(object):
    """CodebaseService manages user codebases (file folders)
    """

    def CreateCodebase(self, request, context):
        """CreateCodebase creates a new codebase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCodebase(self, request, context):
        """GetCodebase retrieves information about a codebase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCodebases(self, request, context):
        """ListCodebases lists all codebases for an owner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCodebase(self, request, context):
        """DeleteCodebase deletes a codebase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFiles(self, request_iterator, context):
        """UploadFiles uploads files to a codebase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """DownloadFile downloads a file from a codebase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """ListFiles lists files in a codebase directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodebaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCodebase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCodebase,
                    request_deserializer=codebase__pb2.CreateCodebaseRequest.FromString,
                    response_serializer=codebase__pb2.Codebase.SerializeToString,
            ),
            'GetCodebase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCodebase,
                    request_deserializer=codebase__pb2.GetCodebaseRequest.FromString,
                    response_serializer=codebase__pb2.Codebase.SerializeToString,
            ),
            'ListCodebases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCodebases,
                    request_deserializer=codebase__pb2.ListCodebasesRequest.FromString,
                    response_serializer=codebase__pb2.ListCodebasesResponse.SerializeToString,
            ),
            'DeleteCodebase': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCodebase,
                    request_deserializer=codebase__pb2.DeleteCodebaseRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'UploadFiles': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=codebase__pb2.UploadChunk.FromString,
                    response_serializer=codebase__pb2.UploadResult.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=codebase__pb2.DownloadFileRequest.FromString,
                    response_serializer=codebase__pb2.FileChunk.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=codebase__pb2.ListFilesRequest.FromString,
                    response_serializer=codebase__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.v1.CodebaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.v1.CodebaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodebaseService(object):
    """CodebaseService manages user codebases (file folders)
    """

    @staticmethod
    def CreateCodebase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.CodebaseService/CreateCodebase',
            codebase__pb2.CreateCodebaseRequest.SerializeToString,
            codebase__pb2.Codebase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCodebase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.CodebaseService/GetCodebase',
            codebase__pb2.GetCodebaseRequest.SerializeToString,
            codebase__pb2.Codebase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCodebases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.CodebaseService/ListCodebases',
            codebase__pb2.ListCodebasesRequest.SerializeToString,
            codebase__pb2.ListCodebasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCodebase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.CodebaseService/DeleteCodebase',
            codebase__pb2.DeleteCodebaseRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFiles(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sandbox.v1.CodebaseService/UploadFiles',
            codebase__pb2.UploadChunk.SerializeToString,
            codebase__pb2.UploadResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sandbox.v1.CodebaseService/DownloadFile',
            codebase__pb2.DownloadFileRequest.SerializeToString,
            codebase__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.CodebaseService/ListFiles',
            codebase__pb2.ListFilesRequest.SerializeToString,
            codebase__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
