# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """SandboxService manages sandbox lifecycle and execution
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/sandbox.v1.SandboxService/CreateSandbox',
                request_serializer=sandbox__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/sandbox.v1.SandboxService/GetSandbox',
                request_serializer=sandbox__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/sandbox.v1.SandboxService/ListSandboxes',
                request_serializer=sandbox__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.StartSandbox = channel.unary_unary(
                '/sandbox.v1.SandboxService/StartSandbox',
                request_serializer=sandbox__pb2.StartSandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.StopSandbox = channel.unary_unary(
                '/sandbox.v1.SandboxService/StopSandbox',
                request_serializer=sandbox__pb2.StopSandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Sandbox.FromString,
                _registered_method=True)
        self.DestroySandbox = channel.unary_unary(
                '/sandbox.v1.SandboxService/DestroySandbox',
                request_serializer=sandbox__pb2.DestroySandboxRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/sandbox.v1.SandboxService/Exec',
                request_serializer=sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecResult.FromString,
                _registered_method=True)
        self.ExecStream = channel.unary_stream(
                '/sandbox.v1.SandboxService/ExecStream',
                request_serializer=sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/sandbox.v1.SandboxService/CreateSession',
                request_serializer=sandbox__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/sandbox.v1.SandboxService/GetSession',
                request_serializer=sandbox__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=sandbox__pb2.Session.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/sandbox.v1.SandboxService/ListSessions',
                request_serializer=sandbox__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/sandbox.v1.SandboxService/DestroySession',
                request_serializer=sandbox__pb2.DestroySessionRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.SessionExec = channel.unary_unary(
                '/sandbox.v1.SandboxService/SessionExec',
                request_serializer=sandbox__pb2.SessionExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecResult.FromString,
                _registered_method=True)
        self.SessionExecStream = channel.unary_stream(
                '/sandbox.v1.SandboxService/SessionExecStream',
                request_serializer=sandbox__pb2.SessionExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecOutput.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """SandboxService manages sandbox lifecycle and execution
    """

    def CreateSandbox(self, request, context):
        """CreateSandbox creates a new sandbox with specified configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """GetSandbox retrieves information about a sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """ListSandboxes lists all sandboxes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSandbox(self, request, context):
        """StartSandbox starts a pending sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSandbox(self, request, context):
        """StopSandbox stops a running sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySandbox(self, request, context):
        """DestroySandbox destroys a sandbox and releases resources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Exec executes a command in a sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecStream(self, request, context):
        """ExecStream executes a command and streams output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """============================================
        Session Management - Stateful Shell Sessions
        ============================================

        CreateSession creates a new shell session within a sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """GetSession retrieves information about a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """ListSessions lists all sessions for a sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """DestroySession destroys a session and kills all its child processes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionExec(self, request, context):
        """SessionExec executes a command within a session (stateful)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionExecStream(self, request, context):
        """SessionExecStream executes a command within a session and streams output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=sandbox__pb2.CreateSandboxRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=sandbox__pb2.GetSandboxRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=sandbox__pb2.ListSandboxesRequest.FromString,
                    response_serializer=sandbox__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'StartSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSandbox,
                    request_deserializer=sandbox__pb2.StartSandboxRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'StopSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSandbox,
                    request_deserializer=sandbox__pb2.StopSandboxRequest.FromString,
                    response_serializer=sandbox__pb2.Sandbox.SerializeToString,
            ),
            'DestroySandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySandbox,
                    request_deserializer=sandbox__pb2.DestroySandboxRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecResult.SerializeToString,
            ),
            'ExecStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecStream,
                    request_deserializer=sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecOutput.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=sandbox__pb2.CreateSessionRequest.FromString,
                    response_serializer=sandbox__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=sandbox__pb2.GetSessionRequest.FromString,
                    response_serializer=sandbox__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=sandbox__pb2.ListSessionsRequest.FromString,
                    response_serializer=sandbox__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=sandbox__pb2.DestroySessionRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'SessionExec': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionExec,
                    request_deserializer=sandbox__pb2.SessionExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecResult.SerializeToString,
            ),
            'SessionExecStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SessionExecStream,
                    request_deserializer=sandbox__pb2.SessionExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """SandboxService manages sandbox lifecycle and execution
    """

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/CreateSandbox',
            sandbox__pb2.CreateSandboxRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/GetSandbox',
            sandbox__pb2.GetSandboxRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/ListSandboxes',
            sandbox__pb2.ListSandboxesRequest.SerializeToString,
            sandbox__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/StartSandbox',
            sandbox__pb2.StartSandboxRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/StopSandbox',
            sandbox__pb2.StopSandboxRequest.SerializeToString,
            sandbox__pb2.Sandbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/DestroySandbox',
            sandbox__pb2.DestroySandboxRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/Exec',
            sandbox__pb2.ExecRequest.SerializeToString,
            sandbox__pb2.ExecResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sandbox.v1.SandboxService/ExecStream',
            sandbox__pb2.ExecRequest.SerializeToString,
            sandbox__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/CreateSession',
            sandbox__pb2.CreateSessionRequest.SerializeToString,
            sandbox__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/GetSession',
            sandbox__pb2.GetSessionRequest.SerializeToString,
            sandbox__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/ListSessions',
            sandbox__pb2.ListSessionsRequest.SerializeToString,
            sandbox__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/DestroySession',
            sandbox__pb2.DestroySessionRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionExec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.SandboxService/SessionExec',
            sandbox__pb2.SessionExecRequest.SerializeToString,
            sandbox__pb2.ExecResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionExecStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sandbox.v1.SandboxService/SessionExecStream',
            sandbox__pb2.SessionExecRequest.SerializeToString,
            sandbox__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
