# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\nsandbox.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x86\x01\n\x0ePermissionRule\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.sandbox.v1.PatternType\x12*\n\npermission\x18\x03 \x01(\x0e\x32\x16.sandbox.v1.Permission\x12\x10\n\x08priority\x18\x04 \x01(\x05\"\x07\n\x05\x45mpty*}\n\nPermission\x12\x1a\n\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x13\n\x0fPERMISSION_NONE\x10\x01\x12\x13\n\x0fPERMISSION_VIEW\x10\x02\x12\x13\n\x0fPERMISSION_READ\x10\x03\x12\x14\n\x10PERMISSION_WRITE\x10\x04*u\n\x0bPatternType\x12\x1c\n\x18PATTERN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11PATTERN_TYPE_GLOB\x10\x01\x12\x1a\n\x16PATTERN_TYPE_DIRECTORY\x10\x02\x12\x15\n\x11PATTERN_TYPE_FILE\x10\x03*\x9d\x01\n\rSandboxStatus\x12\x1e\n\x1aSANDBOX_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16SANDBOX_STATUS_PENDING\x10\x01\x12\x1a\n\x16SANDBOX_STATUS_RUNNING\x10\x02\x12\x1a\n\x16SANDBOX_STATUS_STOPPED\x10\x03\x12\x18\n\x14SANDBOX_STATUS_ERROR\x10\x04\x42>Z<github.com/ajaxzhan/sandbox-rls/api/gen/sandbox/v1;sandboxv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/ajaxzhan/sandbox-rls/api/gen/sandbox/v1;sandboxv1'
  _globals['_PERMISSION']._serialized_start=239
  _globals['_PERMISSION']._serialized_end=364
  _globals['_PATTERNTYPE']._serialized_start=366
  _globals['_PATTERNTYPE']._serialized_end=483
  _globals['_SANDBOXSTATUS']._serialized_start=486
  _globals['_SANDBOXSTATUS']._serialized_end=643
  _globals['_PERMISSIONRULE']._serialized_start=94
  _globals['_PERMISSIONRULE']._serialized_end=228
  _globals['_EMPTY']._serialized_start=230
  _globals['_EMPTY']._serialized_end=237
# @@protoc_insertion_point(module_scope)
